---
- name: Verify
  hosts: all
  become: false
  gather_facts: true

  roles:
    - role: cron
      cron_jobs:
        - name: requested job
          job: "ls -alh > /dev/null"
        - name: requested job by the minute
          minute: "23"
          job: "ls -alh > /dev/null"
        - name: requested job by the hour
          hour: "23"
          job: "ls -alh > /dev/null"
        - name: requested job by the weekday
          weekday: "1"
          job: "ls -alh > /dev/null"
